type faunaBlogHeadlines {
  title: String!
  headline: String!
  category: String!
}

type hits {
  slug: String!
  hits: Int!
  category: String!
}

type Query {
  allFaunaBlogHeadlines: [faunaBlogHeadlines]
  allPageHits: [hits]
}
